// <auto-generated />
using System.Text.Json;
using System.Text.Json.Serialization;
using Apigen.Vaultwarden.Models;

#nullable enable

namespace Apigen.Vaultwarden.Client;

/// <summary>
/// Internal JSON serialization configuration.
/// </summary>
internal static class JsonConfig
{
  /// <summary>
  /// Default JSON serializer options for all API operations.
  /// </summary>
  internal static readonly JsonSerializerOptions Default = CreateOptions();

  private static JsonSerializerOptions CreateOptions()
  {
    JsonSerializerOptions options = new()
    {
      DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull
    };
    options.Converters.Add(new SmartEnumConverterFactory());
    return options;
  }
}
