//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// AccountsPostRegisterFinishRequest from OpenAPI schema.
/// Schema path: #/components/schemas/AccountsPostRegisterFinishRequest
/// </summary>
public class AccountsPostRegisterFinishRequest
{
  [Required]
  [MinLength(0)]
  [MaxLength(256)]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("email")]
  public string? Email { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("emailVerificationToken")]
  public string? EmailVerificationToken { get; set; }

  [Required]
  [MinLength(0)]
  [MaxLength(1000)]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("masterPasswordHash")]
  public string? MasterPasswordHash { get; set; }

  [MinLength(0)]
  [MaxLength(50)]
  [System.Text.Json.Serialization.JsonPropertyName("masterPasswordHint")]
  public string? MasterPasswordHint { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("userSymmetricKey")]
  public string? UserSymmetricKey { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("userAsymmetricKeys")]
  public required KeysRequestModel UserAsymmetricKeys { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("kdf")]
  public KdfType Kdf { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("kdfIterations")]
  public int KdfIterations { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("kdfMemory")]
  public int? KdfMemory { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("kdfParallelism")]
  public int? KdfParallelism { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("organizationUserId")]
  public Guid? OrganizationUserId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("orgInviteToken")]
  public string? OrgInviteToken { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("orgSponsoredFreeFamilyPlanToken")]
  public string? OrgSponsoredFreeFamilyPlanToken { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("acceptEmergencyAccessInviteToken")]
  public string? AcceptEmergencyAccessInviteToken { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("acceptEmergencyAccessId")]
  public Guid? AcceptEmergencyAccessId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("providerInviteToken")]
  public string? ProviderInviteToken { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("providerUserId")]
  public Guid? ProviderUserId { get; set; }
}
