//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// AccountDataRequestModel from OpenAPI schema.
/// Schema path: #/components/schemas/AccountDataRequestModel
/// </summary>
public class AccountDataRequestModel
{
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("ciphers")]
  public List<CipherWithIdRequestModel>? Ciphers { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("folders")]
  public List<FolderWithIdRequestModel>? Folders { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("sends")]
  public List<SendWithIdRequestModel>? Sends { get; set; }
}
