//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// AccountsPostPasswordRequest from OpenAPI schema.
/// Schema path: #/components/schemas/AccountsPostPasswordRequest
/// </summary>
public class AccountsPostPasswordRequest
{
  [MinLength(0)]
  [MaxLength(300)]
  [System.Text.Json.Serialization.JsonPropertyName("masterPasswordHash")]
  public string? MasterPasswordHash { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("otp")]
  public string? Otp { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("authRequestAccessCode")]
  public string? AuthRequestAccessCode { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("secret")]
  public string? Secret { get; set; }

  [Required]
  [MinLength(0)]
  [MaxLength(300)]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("newMasterPasswordHash")]
  public string? NewMasterPasswordHash { get; set; }

  [MinLength(0)]
  [MaxLength(50)]
  [System.Text.Json.Serialization.JsonPropertyName("masterPasswordHint")]
  public string? MasterPasswordHint { get; set; }

  [Required]
  [MinLength(1)]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("key")]
  public string? Key { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("authenticationData")]
  public MasterPasswordAuthenticationDataRequestModel? AuthenticationData { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("unlockData")]
  public MasterPasswordUnlockDataRequestModel? UnlockData { get; set; }
}
