//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// AttachmentResponseModel from OpenAPI schema.
/// Schema path: #/components/schemas/AttachmentResponseModel
/// </summary>
public class AttachmentResponseModel
{
  [System.Text.Json.Serialization.JsonPropertyName("object")]
  public string? Object { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("url")]
  public string? Url { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("fileName")]
  public string? FileName { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("key")]
  public string? Key { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("size")]
  public string? Size { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("sizeName")]
  public string? SizeName { get; set; }
}
