//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// AuthenticatorAttestationRawResponse from OpenAPI schema.
/// Schema path: #/components/schemas/AuthenticatorAttestationRawResponse
/// </summary>
public class AuthenticatorAttestationRawResponse
{
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("rawId")]
  public string? RawId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public PublicKeyCredentialType? Type { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("response")]
  public ResponseData? Response { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("extensions")]
  public AuthenticationExtensionsClientOutputs? Extensions { get; set; }
}
