//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// AuthenticationExtensionsClientOutputs from OpenAPI schema.
/// Schema path: #/components/schemas/AuthenticationExtensionsClientOutputs
/// </summary>
public class AuthenticationExtensionsClientOutputs
{
  [System.Text.Json.Serialization.JsonPropertyName("example.extension")]
  public object? ExampleDotextension { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("appid")]
  public bool? Appid { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("authnSel")]
  public bool? AuthnSel { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("exts")]
  public List<string?>? Exts { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("uvm")]
  public List<List<long>?>? Uvm { get; set; }
}
