//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// AuthRequestsPostRequest from OpenAPI schema.
/// Schema path: #/components/schemas/AuthRequestsPostRequest
/// </summary>
public class AuthRequestsPostRequest
{
  [Required]
  [MinLength(1)]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("email")]
  public string? Email { get; set; }

  [Required]
  [MinLength(1)]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("publicKey")]
  public string? PublicKey { get; set; }

  [Required]
  [MinLength(1)]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("deviceIdentifier")]
  public string? DeviceIdentifier { get; set; }

  [Required]
  [MinLength(0)]
  [MaxLength(25)]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("accessCode")]
  public string? AccessCode { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public AuthRequestType Type { get; set; }
}
