//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// BulkCollectionAccessRequestModel from OpenAPI schema.
/// Schema path: #/components/schemas/BulkCollectionAccessRequestModel
/// </summary>
public class BulkCollectionAccessRequestModel
{
  [System.Text.Json.Serialization.JsonPropertyName("collectionIds")]
  public List<Guid>? CollectionIds { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("groups")]
  public List<SelectionReadOnlyRequestModel>? Groups { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("users")]
  public List<SelectionReadOnlyRequestModel>? Users { get; set; }
}
