//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// CiphersPutRequest from OpenAPI schema.
/// Schema path: #/components/schemas/CiphersPutRequest
/// </summary>
public class CiphersPutRequest
{
  /// <summary>
  /// The Id of the user that encrypted the cipher. It should always represent a UserId.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("encryptedFor")]
  public Guid? EncryptedFor { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public CipherType? Type { get; set; }

  [MinLength(0)]
  [MaxLength(36)]
  [System.Text.Json.Serialization.JsonPropertyName("organizationId")]
  public string? OrganizationId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("folderId")]
  public string? FolderId { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("favorite")]
  public bool? Favorite { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("reprompt")]
  public CipherRepromptType? Reprompt { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("key")]
  public string? Key { get; set; }

  [Required]
  [MinLength(0)]
  [MaxLength(1000)]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  [MinLength(0)]
  [MaxLength(10000)]
  [System.Text.Json.Serialization.JsonPropertyName("notes")]
  public string? Notes { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("fields")]
  public List<CipherFieldModel>? Fields { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("passwordHistory")]
  public List<CipherPasswordHistoryModel>? PasswordHistory { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("attachments")]
  public Dictionary<string, string?>? Attachments { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("attachments2")]
  public Dictionary<string, CipherAttachmentModel>? Attachments2 { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("login")]
  public CipherLoginModel? Login { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("card")]
  public CipherCardModel? Card { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("identity")]
  public CipherIdentityModel? Identity { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("secureNote")]
  public CipherSecureNoteModel? SecureNote { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("sshKey")]
  public CipherSshKeyModel? SshKey { get; set; }

  /// <summary>
  /// JSON string containing cipher-specific data
  /// </summary>
  [MinLength(0)]
  [MaxLength(500000)]
  [System.Text.Json.Serialization.JsonPropertyName("data")]
  public string? Data { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("lastKnownRevisionDate")]
  public DateTime? LastKnownRevisionDate { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("archivedDate")]
  public DateTime? ArchivedDate { get; set; }
}
