//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// CipherLoginModel from OpenAPI schema.
/// Schema path: #/components/schemas/CipherLoginModel
/// </summary>
public class CipherLoginModel
{
  [MinLength(0)]
  [MaxLength(10000)]
  [System.Text.Json.Serialization.JsonPropertyName("uri")]
  public string? Uri { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("uris")]
  public List<CipherLoginUriModel>? Uris { get; set; }

  [MinLength(0)]
  [MaxLength(1000)]
  [System.Text.Json.Serialization.JsonPropertyName("username")]
  public string? Username { get; set; }

  [MinLength(0)]
  [MaxLength(5000)]
  [System.Text.Json.Serialization.JsonPropertyName("password")]
  public string? Password { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("passwordRevisionDate")]
  public DateTime? PasswordRevisionDate { get; set; }

  [MinLength(0)]
  [MaxLength(1000)]
  [System.Text.Json.Serialization.JsonPropertyName("totp")]
  public string? Totp { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("autofillOnPageLoad")]
  public bool? AutofillOnPageLoad { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("fido2Credentials")]
  public List<CipherFido2CredentialModel>? Fido2Credentials { get; set; }
}
