//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// Represents CipherType values
/// </summary>
public enum CipherType
{
    [EnumMember(Value = "1")]
    Login = 1,

    [EnumMember(Value = "2")]
    SecureNote = 2,

    [EnumMember(Value = "3")]
    Card = 3,

    [EnumMember(Value = "4")]
    Identity = 4,

    [EnumMember(Value = "5")]
    SshKey = 5
}
