//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// CipherSSHKeyModel from OpenAPI schema.
/// Schema path: #/components/schemas/CipherSSHKeyModel
/// </summary>
public class CipherSshKeyModel
{
  [MinLength(0)]
  [MaxLength(5000)]
  [System.Text.Json.Serialization.JsonPropertyName("privateKey")]
  public string? PrivateKey { get; set; }

  [MinLength(0)]
  [MaxLength(5000)]
  [System.Text.Json.Serialization.JsonPropertyName("publicKey")]
  public string? PublicKey { get; set; }

  [MinLength(0)]
  [MaxLength(1000)]
  [System.Text.Json.Serialization.JsonPropertyName("keyFingerprint")]
  public string? KeyFingerprint { get; set; }
}
