//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// Cipher from OpenAPI schema.
/// Schema path: #/components/schemas/Cipher
/// </summary>
public class Cipher
{
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public Guid? Id { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("userId")]
  public Guid? UserId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("organizationId")]
  public Guid? OrganizationId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public CipherType? Type { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("data")]
  public string? Data { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("favorites")]
  public string? Favorites { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("folders")]
  public string? Folders { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("attachments")]
  public string? Attachments { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("creationDate")]
  public DateTime? CreationDate { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("revisionDate")]
  public DateTime? RevisionDate { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("deletedDate")]
  public DateTime? DeletedDate { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("reprompt")]
  public CipherRepromptType? Reprompt { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("key")]
  public string? Key { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("archivedDate")]
  public DateTime? ArchivedDate { get; set; }
}
