//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// CipherMiniResponseModel from OpenAPI schema.
/// Schema path: #/components/schemas/CipherMiniResponseModel
/// </summary>
public class CipherMiniResponseModel
{
  [System.Text.Json.Serialization.JsonPropertyName("object")]
  public string? Object { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public Guid? Id { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("organizationId")]
  public Guid? OrganizationId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public CipherType? Type { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("data")]
  public object? Data { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("notes")]
  public string? Notes { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("login")]
  public CipherLoginModel? Login { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("card")]
  public CipherCardModel? Card { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("identity")]
  public CipherIdentityModel? Identity { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("secureNote")]
  public CipherSecureNoteModel? SecureNote { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("sshKey")]
  public CipherSshKeyModel? SshKey { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("fields")]
  public List<CipherFieldModel>? Fields { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("passwordHistory")]
  public List<CipherPasswordHistoryModel>? PasswordHistory { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("attachments")]
  public List<AttachmentResponseModel>? Attachments { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("organizationUseTotp")]
  public bool? OrganizationUseTotp { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("revisionDate")]
  public DateTime? RevisionDate { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("creationDate")]
  public DateTime? CreationDate { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("deletedDate")]
  public DateTime? DeletedDate { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("reprompt")]
  public CipherRepromptType? Reprompt { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("key")]
  public string? Key { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("archivedDate")]
  public DateTime? ArchivedDate { get; set; }
}
