//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// ConfigResponseModel from OpenAPI schema.
/// Schema path: #/components/schemas/ConfigResponseModel
/// </summary>
public class ConfigResponseModel
{
  [System.Text.Json.Serialization.JsonPropertyName("object")]
  public string? Object { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("version")]
  public string? Version { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("gitHash")]
  public string? GitHash { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("server")]
  public ServerConfigResponseModel? Server { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("environment")]
  public EnvironmentConfigResponseModel? Environment { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("featureStates")]
  public Dictionary<string, object?>? FeatureStates { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("push")]
  public PushSettings? Push { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("settings")]
  public ServerSettingsResponseModel? Settings { get; set; }
}
