//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// ConnectTokenRequest from OpenAPI schema.
/// Schema path: #/components/schemas/ConnectTokenRequest
/// </summary>
public class ConnectTokenRequest
{
  /// <summary>
  /// OAuth2 grant type: &apos;password&apos; or &apos;client_credentials&apos;
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("grant_type")]
  public string? GrantType { get; set; }

  /// <summary>
  /// Email address (for password grant)
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("username")]
  public string? Username { get; set; }

  /// <summary>
  /// Base64-encoded master password hash (for password grant)
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("password")]
  public string? Password { get; set; }

  /// <summary>
  /// Requested scopes, e.g. &apos;api offline_access&apos;
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("scope")]
  public string? Scope { get; set; }

  /// <summary>
  /// Client identifier: &apos;cli&apos;, &apos;web&apos;, &apos;browser&apos;, &apos;desktop&apos;, &apos;mobile&apos;, or an API key client_id
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("client_id")]
  public string? ClientId { get; set; }

  /// <summary>
  /// Client secret (for client_credentials grant with API key)
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("client_secret")]
  public string? ClientSecret { get; set; }

  /// <summary>
  /// Device type enum: 9=CLI, 6=WindowsDesktop, 7=MacOsDesktop, etc.
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("deviceType")]
  public int? DeviceType { get; set; }

  /// <summary>
  /// Unique device GUID
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("deviceIdentifier")]
  public string? DeviceIdentifier { get; set; }

  /// <summary>
  /// Device name string, e.g. &apos;cli&apos;
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("deviceName")]
  public string? DeviceName { get; set; }

  /// <summary>
  /// Push notification token (empty for CLI)
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("devicePushToken")]
  public string? DevicePushToken { get; set; }

  /// <summary>
  /// 2FA code (TOTP, YubiKey, etc.)
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("twoFactorToken")]
  public string? TwoFactorToken { get; set; }

  /// <summary>
  /// 2FA provider: 0=Authenticator, 1=Email, 2=Duo, 3=YubiKey, 5=Remember, 7=WebAuthn
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("twoFactorProvider")]
  public int? TwoFactorProvider { get; set; }

  /// <summary>
  /// Set to 1 to remember this device for 2FA
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("twoFactorRemember")]
  public int? TwoFactorRemember { get; set; }
}
