//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// Represents DeviceType values
/// </summary>
public enum DeviceType
{
    [EnumMember(Value = "0")]
    Android = 0,

    [EnumMember(Value = "1")]
    IOS = 1,

    [EnumMember(Value = "2")]
    ChromeExtension = 2,

    [EnumMember(Value = "3")]
    FirefoxExtension = 3,

    [EnumMember(Value = "4")]
    OperaExtension = 4,

    [EnumMember(Value = "5")]
    EdgeExtension = 5,

    [EnumMember(Value = "6")]
    WindowsDesktop = 6,

    [EnumMember(Value = "7")]
    MacOsDesktop = 7,

    [EnumMember(Value = "8")]
    LinuxDesktop = 8,

    [EnumMember(Value = "9")]
    ChromeBrowser = 9,

    [EnumMember(Value = "10")]
    FirefoxBrowser = 10,

    [EnumMember(Value = "11")]
    OperaBrowser = 11,

    [EnumMember(Value = "12")]
    EdgeBrowser = 12,

    [EnumMember(Value = "13")]
    IEBrowser = 13,

    [EnumMember(Value = "14")]
    UnknownBrowser = 14,

    [EnumMember(Value = "15")]
    AndroidAmazon = 15,

    [EnumMember(Value = "16")]
    Uwp = 16,

    [EnumMember(Value = "17")]
    SafariBrowser = 17,

    [EnumMember(Value = "18")]
    VivaldiBrowser = 18,

    [EnumMember(Value = "19")]
    VivaldiExtension = 19,

    [EnumMember(Value = "20")]
    SafariExtension = 20,

    [EnumMember(Value = "21")]
    Sdk = 21,

    [EnumMember(Value = "22")]
    Server = 22,

    [EnumMember(Value = "23")]
    WindowsCli = 23,

    [EnumMember(Value = "24")]
    MacOsCli = 24,

    [EnumMember(Value = "25")]
    LinuxCli = 25,

    [EnumMember(Value = "26")]
    DuckDuckGoBrowser = 26
}
