//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// DeviceAuthRequestResponseModel from OpenAPI schema.
/// Schema path: #/components/schemas/DeviceAuthRequestResponseModel
/// </summary>
public class DeviceAuthRequestResponseModel
{
  [System.Text.Json.Serialization.JsonPropertyName("object")]
  public string? Object { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public Guid? Id { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public DeviceType? Type { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("identifier")]
  public string? Identifier { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("creationDate")]
  public DateTime? CreationDate { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("isTrusted")]
  public bool? IsTrusted { get; set; }

  [MinLength(0)]
  [MaxLength(2000)]
  [System.Text.Json.Serialization.JsonPropertyName("encryptedUserKey")]
  public string? EncryptedUserKey { get; set; }

  [MinLength(0)]
  [MaxLength(2000)]
  [System.Text.Json.Serialization.JsonPropertyName("encryptedPublicKey")]
  public string? EncryptedPublicKey { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("devicePendingAuthRequest")]
  public PendingAuthRequest? DevicePendingAuthRequest { get; set; }
}
