//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// DomainsResponseModel from OpenAPI schema.
/// Schema path: #/components/schemas/DomainsResponseModel
/// </summary>
public class DomainsResponseModel
{
  [System.Text.Json.Serialization.JsonPropertyName("object")]
  public string? Object { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("equivalentDomains")]
  public List<List<string?>?>? EquivalentDomains { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("globalEquivalentDomains")]
  public List<GlobalDomains>? GlobalEquivalentDomains { get; set; }
}
