//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// EmergencyAccessWithIdRequestModel from OpenAPI schema.
/// Schema path: #/components/schemas/EmergencyAccessWithIdRequestModel
/// </summary>
public class EmergencyAccessWithIdRequestModel
{
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public EmergencyAccessType Type { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("waitTimeDays")]
  public int WaitTimeDays { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("keyEncrypted")]
  public string? KeyEncrypted { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public Guid Id { get; set; }
}
