//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.ComponentModel;
using System.Reflection;
using System.Runtime.Serialization;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// Extension methods for enhanced enum functionality
/// </summary>
public static class EnumExtensions
{
    /// <summary>
    /// Gets the description of an enum value from the Description attribute
    /// </summary>
    public static string GetDescription<TEnum>(this TEnum enumValue) where TEnum : struct, Enum
    {
        var field = typeof(TEnum).GetField(enumValue.ToString());
        if (field == null) return enumValue.ToString();

        var descriptionAttr = field.GetCustomAttribute<DescriptionAttribute>();
        return descriptionAttr?.Description ?? enumValue.ToString();
    }

    /// <summary>
    /// Gets the raw API value for an enum (from EnumMember attribute or numeric conversion)
    /// </summary>
    public static string GetRawValue<TEnum>(this TEnum enumValue) where TEnum : struct, Enum
    {
        var field = typeof(TEnum).GetField(enumValue.ToString());
        if (field == null) return enumValue.ToString();

        var enumMemberAttr = field.GetCustomAttribute<EnumMemberAttribute>();
        if (enumMemberAttr?.Value != null)
        {
            return enumMemberAttr.Value;
        }

        // For _1 style enums, return the numeric part
        var enumName = enumValue.ToString();
        if (enumName.StartsWith("_") && int.TryParse(enumName.Substring(1), out var numericValue))
        {
            return numericValue.ToString();
        }

        return enumName;
    }

    /// <summary>
    /// Checks if an enum value represents an unknown/undefined value
    /// </summary>
    public static bool IsUnknown<TEnum>(this TEnum enumValue) where TEnum : struct, Enum
    {
        var name = enumValue.ToString();
        return name.Equals("Unknown", StringComparison.OrdinalIgnoreCase) ||
               Convert.ToInt32(enumValue) == -1;
    }

    /// <summary>
    /// Gets all enum values with their descriptions
    /// </summary>
    public static Dictionary<TEnum, string> GetAllDescriptions<TEnum>() where TEnum : struct, Enum
    {
        var result = new Dictionary<TEnum, string>();

        foreach (TEnum enumValue in Enum.GetValues<TEnum>())
        {
            result[enumValue] = enumValue.GetDescription();
        }

        return result;
    }

    /// <summary>
    /// Tries to parse a raw API value to an enum
    /// </summary>
    public static bool TryParseRawValue<TEnum>(string rawValue, out TEnum result) where TEnum : struct, Enum
    {
        result = default;

        if (string.IsNullOrEmpty(rawValue))
            return false;

        // Try direct enum parse first
        if (Enum.TryParse<TEnum>(rawValue, true, out result))
            return true;

        // Try numeric conversion
        if (int.TryParse(rawValue, out var numericValue))
        {
            // Try with underscore prefix
            if (Enum.TryParse<TEnum>($"_{numericValue}", true, out result))
                return true;

            // Try direct cast
            if (Enum.IsDefined(typeof(TEnum), numericValue))
            {
                result = (TEnum)(object)numericValue;
                return true;
            }
        }

        // Try finding by EnumMember attribute
        foreach (TEnum enumValue in Enum.GetValues<TEnum>())
        {
            if (enumValue.GetRawValue().Equals(rawValue, StringComparison.OrdinalIgnoreCase))
            {
                result = enumValue;
                return true;
            }
        }

        return false;
    }
}
