//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// EnvironmentConfigResponseModel from OpenAPI schema.
/// Schema path: #/components/schemas/EnvironmentConfigResponseModel
/// </summary>
public class EnvironmentConfigResponseModel
{
  [System.Text.Json.Serialization.JsonPropertyName("cloudRegion")]
  public string? CloudRegion { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("vault")]
  public string? Vault { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("api")]
  public string? Api { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("identity")]
  public string? Identity { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("notifications")]
  public string? Notifications { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("sso")]
  public string? Sso { get; set; }
}
