//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// ErrorResponseModel from OpenAPI schema.
/// Schema path: #/components/schemas/ErrorResponseModel
/// </summary>
public class ErrorResponseModel
{
  /// <summary>
  /// String representing the object&apos;s type. Objects of the same type share the same properties.
  /// </summary>
  [Required]
  [MinLength(1)]
  [System.Text.Json.Serialization.JsonPropertyName("object")]
  public string? Object { get; set; }

  /// <summary>
  /// A human-readable message providing details about the error.
  /// </summary>
  [Required]
  [MinLength(1)]
  [System.Text.Json.Serialization.JsonPropertyName("message")]
  public string? Message { get; set; }

  /// <summary>
  /// If multiple errors occurred, they are listed in dictionary. Errors related to a specific
  /// request parameter will include a dictionary key describing that parameter.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("errors")]
  public Dictionary<string, List<string?>?>? Errors { get; set; }
}
