//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// Represents EventType values
/// </summary>
public enum EventType
{
    [EnumMember(Value = "1000")]
    UserLoggedIn = 1000,

    [EnumMember(Value = "1001")]
    UserChangedPassword = 1001,

    [EnumMember(Value = "1002")]
    UserUpdated2Fa = 1002,

    [EnumMember(Value = "1003")]
    UserDisabled2Fa = 1003,

    [EnumMember(Value = "1004")]
    UserRecovered2Fa = 1004,

    [EnumMember(Value = "1005")]
    UserFailedLogIn = 1005,

    [EnumMember(Value = "1006")]
    UserFailedLogIn2Fa = 1006,

    [EnumMember(Value = "1007")]
    UserClientExportedVault = 1007,

    [EnumMember(Value = "1008")]
    UserUpdatedTempPassword = 1008,

    [EnumMember(Value = "1009")]
    UserMigratedKeyToKeyConnector = 1009,

    [EnumMember(Value = "1010")]
    UserRequestedDeviceApproval = 1010,

    [EnumMember(Value = "1011")]
    UserTdeOffboardingPasswordSet = 1011,

    [EnumMember(Value = "1100")]
    CipherCreated = 1100,

    [EnumMember(Value = "1101")]
    CipherUpdated = 1101,

    [EnumMember(Value = "1102")]
    CipherDeleted = 1102,

    [EnumMember(Value = "1103")]
    CipherAttachmentCreated = 1103,

    [EnumMember(Value = "1104")]
    CipherAttachmentDeleted = 1104,

    [EnumMember(Value = "1105")]
    CipherShared = 1105,

    [EnumMember(Value = "1106")]
    CipherUpdatedCollections = 1106,

    [EnumMember(Value = "1107")]
    CipherClientViewed = 1107,

    [EnumMember(Value = "1108")]
    CipherClientToggledPasswordVisible = 1108,

    [EnumMember(Value = "1109")]
    CipherClientToggledHiddenFieldVisible = 1109,

    [EnumMember(Value = "1110")]
    CipherClientToggledCardCodeVisible = 1110,

    [EnumMember(Value = "1111")]
    CipherClientCopiedPassword = 1111,

    [EnumMember(Value = "1112")]
    CipherClientCopiedHiddenField = 1112,

    [EnumMember(Value = "1113")]
    CipherClientCopiedCardCode = 1113,

    [EnumMember(Value = "1114")]
    CipherClientAutofilled = 1114,

    [EnumMember(Value = "1115")]
    CipherSoftDeleted = 1115,

    [EnumMember(Value = "1116")]
    CipherRestored = 1116,

    [EnumMember(Value = "1117")]
    CipherClientToggledCardNumberVisible = 1117,

    [EnumMember(Value = "1300")]
    CollectionCreated = 1300,

    [EnumMember(Value = "1301")]
    CollectionUpdated = 1301,

    [EnumMember(Value = "1302")]
    CollectionDeleted = 1302,

    [EnumMember(Value = "1400")]
    GroupCreated = 1400,

    [EnumMember(Value = "1401")]
    GroupUpdated = 1401,

    [EnumMember(Value = "1402")]
    GroupDeleted = 1402,

    [EnumMember(Value = "1500")]
    OrganizationUserInvited = 1500,

    [EnumMember(Value = "1501")]
    OrganizationUserConfirmed = 1501,

    [EnumMember(Value = "1502")]
    OrganizationUserUpdated = 1502,

    [EnumMember(Value = "1503")]
    OrganizationUserRemoved = 1503,

    [EnumMember(Value = "1504")]
    OrganizationUserUpdatedGroups = 1504,

    [EnumMember(Value = "1505")]
    OrganizationUserUnlinkedSso = 1505,

    [EnumMember(Value = "1506")]
    OrganizationUserResetPasswordEnroll = 1506,

    [EnumMember(Value = "1507")]
    OrganizationUserResetPasswordWithdraw = 1507,

    [EnumMember(Value = "1508")]
    OrganizationUserAdminResetPassword = 1508,

    [EnumMember(Value = "1509")]
    OrganizationUserResetSsoLink = 1509,

    [EnumMember(Value = "1510")]
    OrganizationUserFirstSsoLogin = 1510,

    [EnumMember(Value = "1511")]
    OrganizationUserRevoked = 1511,

    [EnumMember(Value = "1512")]
    OrganizationUserRestored = 1512,

    [EnumMember(Value = "1513")]
    OrganizationUserApprovedAuthRequest = 1513,

    [EnumMember(Value = "1514")]
    OrganizationUserRejectedAuthRequest = 1514,

    [EnumMember(Value = "1515")]
    OrganizationUserDeleted = 1515,

    [EnumMember(Value = "1516")]
    OrganizationUserLeft = 1516,

    [EnumMember(Value = "1517")]
    OrganizationUserAutomaticallyConfirmed = 1517,

    [EnumMember(Value = "1600")]
    OrganizationUpdated = 1600,

    [EnumMember(Value = "1601")]
    OrganizationPurgedVault = 1601,

    [EnumMember(Value = "1602")]
    OrganizationClientExportedVault = 1602,

    [EnumMember(Value = "1603")]
    OrganizationVaultAccessed = 1603,

    [EnumMember(Value = "1604")]
    OrganizationEnabledSso = 1604,

    [EnumMember(Value = "1605")]
    OrganizationDisabledSso = 1605,

    [EnumMember(Value = "1606")]
    OrganizationEnabledKeyConnector = 1606,

    [EnumMember(Value = "1607")]
    OrganizationDisabledKeyConnector = 1607,

    [EnumMember(Value = "1608")]
    OrganizationSponsorshipsSynced = 1608,

    [EnumMember(Value = "1609")]
    OrganizationCollectionManagementUpdated = 1609,

    [EnumMember(Value = "1610")]
    OrganizationCollectionManagementLimitCollectionCreationEnabled = 1610,

    [EnumMember(Value = "1611")]
    OrganizationCollectionManagementLimitCollectionCreationDisabled = 1611,

    [EnumMember(Value = "1612")]
    OrganizationCollectionManagementLimitCollectionDeletionEnabled = 1612,

    [EnumMember(Value = "1613")]
    OrganizationCollectionManagementLimitCollectionDeletionDisabled = 1613,

    [EnumMember(Value = "1614")]
    OrganizationCollectionManagementLimitItemDeletionEnabled = 1614,

    [EnumMember(Value = "1615")]
    OrganizationCollectionManagementLimitItemDeletionDisabled = 1615,

    [EnumMember(Value = "1616")]
    OrganizationCollectionManagementAllowAdminAccessToAllCollectionItemsEnabled = 1616,

    [EnumMember(Value = "1617")]
    OrganizationCollectionManagementAllowAdminAccessToAllCollectionItemsDisabled = 1617,

    [EnumMember(Value = "1700")]
    PolicyUpdated = 1700,

    [EnumMember(Value = "1800")]
    ProviderUserInvited = 1800,

    [EnumMember(Value = "1801")]
    ProviderUserConfirmed = 1801,

    [EnumMember(Value = "1802")]
    ProviderUserUpdated = 1802,

    [EnumMember(Value = "1803")]
    ProviderUserRemoved = 1803,

    [EnumMember(Value = "1900")]
    ProviderOrganizationCreated = 1900,

    [EnumMember(Value = "1901")]
    ProviderOrganizationAdded = 1901,

    [EnumMember(Value = "1902")]
    ProviderOrganizationRemoved = 1902,

    [EnumMember(Value = "1903")]
    ProviderOrganizationVaultAccessed = 1903,

    [EnumMember(Value = "2000")]
    OrganizationDomainAdded = 2000,

    [EnumMember(Value = "2001")]
    OrganizationDomainRemoved = 2001,

    [EnumMember(Value = "2002")]
    OrganizationDomainVerified = 2002,

    [EnumMember(Value = "2003")]
    OrganizationDomainNotVerified = 2003,

    [EnumMember(Value = "2100")]
    SecretRetrieved = 2100,

    [EnumMember(Value = "2101")]
    SecretCreated = 2101,

    [EnumMember(Value = "2102")]
    SecretEdited = 2102,

    [EnumMember(Value = "2103")]
    SecretDeleted = 2103,

    [EnumMember(Value = "2104")]
    SecretPermanentlyDeleted = 2104,

    [EnumMember(Value = "2105")]
    SecretRestored = 2105,

    [EnumMember(Value = "2200")]
    ProjectRetrieved = 2200,

    [EnumMember(Value = "2201")]
    ProjectCreated = 2201,

    [EnumMember(Value = "2202")]
    ProjectEdited = 2202,

    [EnumMember(Value = "2203")]
    ProjectDeleted = 2203,

    [EnumMember(Value = "2300")]
    ServiceAccountUserAdded = 2300,

    [EnumMember(Value = "2301")]
    ServiceAccountUserRemoved = 2301,

    [EnumMember(Value = "2302")]
    ServiceAccountGroupAdded = 2302,

    [EnumMember(Value = "2303")]
    ServiceAccountGroupRemoved = 2303,

    [EnumMember(Value = "2304")]
    ServiceAccountCreated = 2304,

    [EnumMember(Value = "2305")]
    ServiceAccountDeleted = 2305
}
