//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// EventResponseModel from OpenAPI schema.
/// Schema path: #/components/schemas/EventResponseModel
/// </summary>
public class EventResponseModel
{
  [System.Text.Json.Serialization.JsonPropertyName("object")]
  public string? Object { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public EventType? Type { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("userId")]
  public Guid? UserId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("organizationId")]
  public Guid? OrganizationId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("providerId")]
  public Guid? ProviderId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("cipherId")]
  public Guid? CipherId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("collectionId")]
  public Guid? CollectionId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("groupId")]
  public Guid? GroupId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("policyId")]
  public Guid? PolicyId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("organizationUserId")]
  public Guid? OrganizationUserId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("providerUserId")]
  public Guid? ProviderUserId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("providerOrganizationId")]
  public Guid? ProviderOrganizationId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("actingUserId")]
  public Guid? ActingUserId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("installationId")]
  public Guid? InstallationId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("date")]
  public DateTime? Date { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("deviceType")]
  public DeviceType? DeviceType { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("ipAddress")]
  public string? IpAddress { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("systemUser")]
  public EventSystemUser? SystemUser { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("domainName")]
  public string? DomainName { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("secretId")]
  public Guid? SecretId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("projectId")]
  public Guid? ProjectId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("serviceAccountId")]
  public Guid? ServiceAccountId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("grantedServiceAccountId")]
  public Guid? GrantedServiceAccountId { get; set; }
}
