//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// Represents GlobalEquivalentDomainsType values
/// </summary>
public enum GlobalEquivalentDomainsType
{
    [EnumMember(Value = "0")]
    Google = 0,

    [EnumMember(Value = "1")]
    Apple = 1,

    [EnumMember(Value = "2")]
    Ameritrade = 2,

    [EnumMember(Value = "3")]
    BoA = 3,

    [EnumMember(Value = "4")]
    Sprint = 4,

    [EnumMember(Value = "5")]
    WellsFargo = 5,

    [EnumMember(Value = "6")]
    Merrill = 6,

    [EnumMember(Value = "7")]
    Citi = 7,

    [EnumMember(Value = "8")]
    Cnet = 8,

    [EnumMember(Value = "9")]
    Gap = 9,

    [EnumMember(Value = "10")]
    Microsoft = 10,

    [EnumMember(Value = "11")]
    United = 11,

    [EnumMember(Value = "12")]
    Yahoo = 12,

    [EnumMember(Value = "13")]
    Zonelabs = 13,

    [EnumMember(Value = "14")]
    PayPal = 14,

    [EnumMember(Value = "15")]
    Avon = 15,

    [EnumMember(Value = "16")]
    Diapers = 16,

    [EnumMember(Value = "17")]
    Contacts = 17,

    [EnumMember(Value = "18")]
    Amazon = 18,

    [EnumMember(Value = "19")]
    Cox = 19,

    [EnumMember(Value = "20")]
    Norton = 20,

    [EnumMember(Value = "21")]
    Verizon = 21,

    [EnumMember(Value = "22")]
    Buy = 22,

    [EnumMember(Value = "23")]
    Sirius = 23,

    [EnumMember(Value = "24")]
    Ea = 24,

    [EnumMember(Value = "25")]
    Basecamp = 25,

    [EnumMember(Value = "26")]
    Steam = 26,

    [EnumMember(Value = "27")]
    Chart = 27,

    [EnumMember(Value = "28")]
    Gotomeeting = 28,

    [EnumMember(Value = "29")]
    Gogo = 29,

    [EnumMember(Value = "30")]
    Oracle = 30,

    [EnumMember(Value = "31")]
    Discover = 31,

    [EnumMember(Value = "32")]
    Dcu = 32,

    [EnumMember(Value = "33")]
    Healthcare = 33,

    [EnumMember(Value = "34")]
    Pepco = 34,

    [EnumMember(Value = "35")]
    Century21 = 35,

    [EnumMember(Value = "36")]
    Comcast = 36,

    [EnumMember(Value = "37")]
    Cricket = 37,

    [EnumMember(Value = "38")]
    Mtb = 38,

    [EnumMember(Value = "39")]
    Dropbox = 39,

    [EnumMember(Value = "40")]
    Snapfish = 40,

    [EnumMember(Value = "41")]
    Alibaba = 41,

    [EnumMember(Value = "42")]
    Playstation = 42,

    [EnumMember(Value = "43")]
    Mercado = 43,

    [EnumMember(Value = "44")]
    Zendesk = 44,

    [EnumMember(Value = "45")]
    Autodesk = 45,

    [EnumMember(Value = "46")]
    RailNation = 46,

    [EnumMember(Value = "47")]
    Wpcu = 47,

    [EnumMember(Value = "48")]
    Mathletics = 48,

    [EnumMember(Value = "49")]
    Discountbank = 49,

    [EnumMember(Value = "50")]
    Mi = 50,

    [EnumMember(Value = "51")]
    Facebook = 51,

    [EnumMember(Value = "52")]
    Postepay = 52,

    [EnumMember(Value = "53")]
    Skysports = 53,

    [EnumMember(Value = "54")]
    Disney = 54,

    [EnumMember(Value = "55")]
    Pokemon = 55,

    [EnumMember(Value = "56")]
    Uv = 56,

    [EnumMember(Value = "57")]
    Yahavo = 57,

    [EnumMember(Value = "58")]
    Mdsol = 58,

    [EnumMember(Value = "59")]
    Sears = 59,

    [EnumMember(Value = "60")]
    Xiami = 60,

    [EnumMember(Value = "61")]
    Belkin = 61,

    [EnumMember(Value = "62")]
    Turbotax = 62,

    [EnumMember(Value = "63")]
    Shopify = 63,

    [EnumMember(Value = "64")]
    Ebay = 64,

    [EnumMember(Value = "65")]
    Techdata = 65,

    [EnumMember(Value = "66")]
    Schwab = 66,

    [EnumMember(Value = "67")]
    Mozilla = 67,

    [EnumMember(Value = "68")]
    Tesla = 68,

    [EnumMember(Value = "69")]
    MorganStanley = 69,

    [EnumMember(Value = "70")]
    TaxAct = 70,

    [EnumMember(Value = "71")]
    Wikimedia = 71,

    [EnumMember(Value = "72")]
    Airbnb = 72,

    [EnumMember(Value = "73")]
    Eventbrite = 73,

    [EnumMember(Value = "74")]
    StackExchange = 74,

    [EnumMember(Value = "75")]
    Docusign = 75,

    [EnumMember(Value = "76")]
    Envato = 76,

    [EnumMember(Value = "77")]
    X10Hosting = 77,

    [EnumMember(Value = "78")]
    Cisco = 78,

    [EnumMember(Value = "79")]
    CedarFair = 79,

    [EnumMember(Value = "80")]
    Ubiquiti = 80,

    [EnumMember(Value = "81")]
    Discord = 81,

    [EnumMember(Value = "82")]
    Netcup = 82,

    [EnumMember(Value = "83")]
    Yandex = 83,

    [EnumMember(Value = "84")]
    Sony = 84,

    [EnumMember(Value = "85")]
    Proton = 85,

    [EnumMember(Value = "86")]
    Ubisoft = 86,

    [EnumMember(Value = "87")]
    TransferWise = 87,

    [EnumMember(Value = "88")]
    TakeawayEU = 88,

    [EnumMember(Value = "89")]
    Atlassian = 89,

    [EnumMember(Value = "90")]
    Pinterest = 90
}
