//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// KdfSettings from OpenAPI schema.
/// Schema path: #/components/schemas/KdfSettings
/// </summary>
public class KdfSettings
{
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("kdfType")]
  public KdfType KdfType { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("iterations")]
  public int Iterations { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("memory")]
  public int? Memory { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("parallelism")]
  public int? Parallelism { get; set; }
}
