//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// MasterPasswordAuthenticationDataRequestModel from OpenAPI schema.
/// Schema path: #/components/schemas/MasterPasswordAuthenticationDataRequestModel
/// </summary>
public class MasterPasswordAuthenticationDataRequestModel
{
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("kdf")]
  public KdfRequestModel Kdf { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("masterPasswordAuthenticationHash")]
  public string? MasterPasswordAuthenticationHash { get; set; }

  [Required]
  [MinLength(0)]
  [MaxLength(256)]
  [System.Text.Json.Serialization.JsonPropertyName("salt")]
  public string? Salt { get; set; }
}
