//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// MasterPasswordUnlockResponseModel from OpenAPI schema.
/// Schema path: #/components/schemas/MasterPasswordUnlockResponseModel
/// </summary>
public class MasterPasswordUnlockResponseModel
{
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("kdf")]
  public MasterPasswordUnlockKdfResponseModel Kdf { get; set; } = null!;

  /// <summary>
  /// The user&apos;s symmetric key encrypted with their master key.
  /// Also known as &quot;MasterKeyWrappedUserKey&quot;
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("masterKeyEncryptedUserKey")]
  public string? MasterKeyEncryptedUserKey { get; set; }

  [Required]
  [MinLength(0)]
  [MaxLength(256)]
  [System.Text.Json.Serialization.JsonPropertyName("salt")]
  public string? Salt { get; set; }
}
