//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// MasterPasswordPolicyResponseModel from OpenAPI schema.
/// Schema path: #/components/schemas/MasterPasswordPolicyResponseModel
/// </summary>
public class MasterPasswordPolicyResponseModel
{
  [System.Text.Json.Serialization.JsonPropertyName("object")]
  public string? Object { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("minComplexity")]
  public int? MinComplexity { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("minLength")]
  public int? MinLength { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("requireLower")]
  public bool? RequireLower { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("requireUpper")]
  public bool? RequireUpper { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("requireNumbers")]
  public bool? RequireNumbers { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("requireSpecial")]
  public bool? RequireSpecial { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("enforceOnLogin")]
  public bool? EnforceOnLogin { get; set; }
}
