//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// OrganizationUsersInviteRequest from OpenAPI schema.
/// Schema path: #/components/schemas/OrganizationUsersInviteRequest
/// </summary>
public class OrganizationUsersInviteRequest
{
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("emails")]
  public List<string?>? Emails { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public OrganizationUserType Type { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("accessSecretsManager")]
  public bool? AccessSecretsManager { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("permissions")]
  public Permissions? Permissions { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("collections")]
  public List<SelectionReadOnlyRequestModel>? Collections { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("groups")]
  public List<Guid>? Groups { get; set; }
}
