//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// OrganizationUserUserMiniDetailsResponseModel from OpenAPI schema.
/// Schema path: #/components/schemas/OrganizationUserUserMiniDetailsResponseModel
/// </summary>
public class OrganizationUserUserMiniDetailsResponseModel
{
  [System.Text.Json.Serialization.JsonPropertyName("object")]
  public string? Object { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public Guid? Id { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("userId")]
  public Guid? UserId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public OrganizationUserType? Type { get; set; }

  /// <summary>
  /// Represents the different stages of a member&apos;s lifecycle in an organization.
  /// The Bit.Core.Entities.OrganizationUser object is populated differently depending on their Status.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("status")]
  public OrganizationUserStatusType? Status { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("email")]
  public string? Email { get; set; }
}
