//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// OrganizationImportRequestModel from OpenAPI schema.
/// Schema path: #/components/schemas/OrganizationImportRequestModel
/// </summary>
public class OrganizationImportRequestModel
{
  /// <summary>
  /// Groups to import.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("groups")]
  public List<OrganizationImportGroupRequestModel>? Groups { get; set; }

  /// <summary>
  /// Members to import.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("members")]
  public List<OrganizationImportMemberRequestModel>? Members { get; set; }

  /// <summary>
  /// Determines if the data in this request should overwrite or append to the existing organization data.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("overwriteExisting")]
  public bool OverwriteExisting { get; set; }

  /// <summary>
  /// Indicates an import of over 2000 users and/or groups is expected
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("largeImport")]
  public bool? LargeImport { get; set; }
}
