//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// OrganizationImportMemberRequestModel from OpenAPI schema.
/// Schema path: #/components/schemas/OrganizationImportMemberRequestModel
/// </summary>
public class OrganizationImportMemberRequestModel
{
  /// <summary>
  /// The member&apos;s email address. Required for non-deleted users.
  /// </summary>
  [MinLength(0)]
  [MaxLength(256)]
  [EmailAddress]
  [System.Text.Json.Serialization.JsonPropertyName("email")]
  public string? Email { get; set; }

  /// <summary>
  /// External identifier for reference or linking this member to another system, such as a user directory.
  /// </summary>
  [Required]
  [MinLength(0)]
  [MaxLength(300)]
  [System.Text.Json.Serialization.JsonPropertyName("externalId")]
  public string? ExternalId { get; set; }

  /// <summary>
  /// Determines if this member should be removed from the organization during import.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("deleted")]
  public bool? Deleted { get; set; }
}
