//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// OrganizationResponseModel from OpenAPI schema.
/// Schema path: #/components/schemas/OrganizationResponseModel
/// </summary>
public class OrganizationResponseModel
{
  [System.Text.Json.Serialization.JsonPropertyName("object")]
  public string? Object { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public Guid? Id { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("businessName")]
  public string? BusinessName { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("businessAddress1")]
  public string? BusinessAddress1 { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("businessAddress2")]
  public string? BusinessAddress2 { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("businessAddress3")]
  public string? BusinessAddress3 { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("businessCountry")]
  public string? BusinessCountry { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("businessTaxNumber")]
  public string? BusinessTaxNumber { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("billingEmail")]
  public string? BillingEmail { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("plan")]
  public PlanResponseModel? Plan { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("secretsManagerPlan")]
  public PlanResponseModel? SecretsManagerPlan { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("planType")]
  public PlanType? PlanType { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("seats")]
  public int? Seats { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("maxAutoscaleSeats")]
  public int? MaxAutoscaleSeats { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("maxCollections")]
  public int? MaxCollections { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("maxStorageGb")]
  public int? MaxStorageGb { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("usePolicies")]
  public bool? UsePolicies { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("useSso")]
  public bool? UseSso { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("useKeyConnector")]
  public bool? UseKeyConnector { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("useScim")]
  public bool? UseScim { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("useGroups")]
  public bool? UseGroups { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("useDirectory")]
  public bool? UseDirectory { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("useEvents")]
  public bool? UseEvents { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("useTotp")]
  public bool? UseTotp { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("use2fa")]
  public bool? Use2Fa { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("useApi")]
  public bool? UseApi { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("useSecretsManager")]
  public bool? UseSecretsManager { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("useResetPassword")]
  public bool? UseResetPassword { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("usersGetPremium")]
  public bool? UsersGetPremium { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("useCustomPermissions")]
  public bool? UseCustomPermissions { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("selfHost")]
  public bool? SelfHost { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("hasPublicAndPrivateKeys")]
  public bool? HasPublicAndPrivateKeys { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("usePasswordManager")]
  public bool? UsePasswordManager { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("smSeats")]
  public int? SmSeats { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("smServiceAccounts")]
  public int? SmServiceAccounts { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("maxAutoscaleSmSeats")]
  public int? MaxAutoscaleSmSeats { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("maxAutoscaleSmServiceAccounts")]
  public int? MaxAutoscaleSmServiceAccounts { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("limitCollectionCreation")]
  public bool? LimitCollectionCreation { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("limitCollectionDeletion")]
  public bool? LimitCollectionDeletion { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("limitItemDeletion")]
  public bool? LimitItemDeletion { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("allowAdminAccessToAllCollectionItems")]
  public bool? AllowAdminAccessToAllCollectionItems { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("useRiskInsights")]
  public bool? UseRiskInsights { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("useOrganizationDomains")]
  public bool? UseOrganizationDomains { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("useAdminSponsoredFamilies")]
  public bool? UseAdminSponsoredFamilies { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("useAutomaticUserConfirmation")]
  public bool? UseAutomaticUserConfirmation { get; set; }
}
