//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// OrganizationImportGroupRequestModel from OpenAPI schema.
/// Schema path: #/components/schemas/OrganizationImportGroupRequestModel
/// </summary>
public class OrganizationImportGroupRequestModel
{
  /// <summary>
  /// The name of the group.
  /// </summary>
  [Required]
  [MinLength(0)]
  [MaxLength(100)]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// External identifier for reference or linking this group to another system, such as a user directory.
  /// </summary>
  [Required]
  [MinLength(0)]
  [MaxLength(300)]
  [System.Text.Json.Serialization.JsonPropertyName("externalId")]
  public string? ExternalId { get; set; }

  /// <summary>
  /// The associated external ids for members in this group.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("memberExternalIds")]
  public List<string?>? MemberExternalIds { get; set; }
}
