//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// OrganizationUserUserDetailsResponseModel from OpenAPI schema.
/// Schema path: #/components/schemas/OrganizationUserUserDetailsResponseModel
/// </summary>
public class OrganizationUserUserDetailsResponseModel
{
  [System.Text.Json.Serialization.JsonPropertyName("object")]
  public string? Object { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public Guid? Id { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("userId")]
  public Guid? UserId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public OrganizationUserType? Type { get; set; }

  /// <summary>
  /// Represents the different stages of a member&apos;s lifecycle in an organization.
  /// The Bit.Core.Entities.OrganizationUser object is populated differently depending on their Status.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("status")]
  public OrganizationUserStatusType? Status { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("externalId")]
  public string? ExternalId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("accessSecretsManager")]
  public bool? AccessSecretsManager { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("permissions")]
  public Permissions? Permissions { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("resetPasswordEnrolled")]
  public bool? ResetPasswordEnrolled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("usesKeyConnector")]
  public bool? UsesKeyConnector { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("hasMasterPassword")]
  public bool? HasMasterPassword { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("email")]
  public string? Email { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("avatarColor")]
  public string? AvatarColor { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("twoFactorEnabled")]
  public bool? TwoFactorEnabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("ssoBound")]
  public bool? SsoBound { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("managedByOrganization")]
  public bool? ManagedByOrganization { get; set; }

  /// <summary>
  /// Indicates if the organization claimed the user. If a user is &quot;claimed&quot; by an organization,
  /// the organization has greater control over their account, and some user actions are restricted.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("claimedByOrganization")]
  public bool? ClaimedByOrganization { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("collections")]
  public List<SelectionReadOnlyResponseModel>? Collections { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("groups")]
  public List<Guid>? Groups { get; set; }
}
