//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// OrganizationsPutRequest from OpenAPI schema.
/// Schema path: #/components/schemas/OrganizationsPutRequest
/// </summary>
public class OrganizationsPutRequest
{
  [MinLength(0)]
  [MaxLength(50)]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  [MinLength(0)]
  [MaxLength(256)]
  [EmailAddress]
  [System.Text.Json.Serialization.JsonPropertyName("billingEmail")]
  public string? BillingEmail { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("keys")]
  public OrganizationKeysRequestModel? Keys { get; set; }
}
