//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// Represents the different stages of a member&apos;s lifecycle in an organization.
/// The Bit.Core.Entities.OrganizationUser object is populated differently depending on their Status.
/// </summary>
public enum OrganizationUserStatusType
{
    [EnumMember(Value = "-1")]
    Revoked = -1,

    [EnumMember(Value = "0")]
    Invited = 0,

    [EnumMember(Value = "1")]
    Accepted = 1,

    [EnumMember(Value = "2")]
    Confirmed = 2
}
