//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// OrganizationCreateRequestModel from OpenAPI schema.
/// Schema path: #/components/schemas/OrganizationCreateRequestModel
/// </summary>
public class OrganizationCreateRequestModel
{
  [Required]
  [MinLength(0)]
  [MaxLength(50)]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  [MinLength(0)]
  [MaxLength(50)]
  [System.Text.Json.Serialization.JsonPropertyName("businessName")]
  public string? BusinessName { get; set; }

  [Required]
  [MinLength(0)]
  [MaxLength(256)]
  [EmailAddress]
  [System.Text.Json.Serialization.JsonPropertyName("billingEmail")]
  public string? BillingEmail { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("planType")]
  public PlanType? PlanType { get; set; }

  [Required]
  [MinLength(1)]
  [System.Text.Json.Serialization.JsonPropertyName("key")]
  public string? Key { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("keys")]
  public OrganizationKeysRequestModel? Keys { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("paymentMethodType")]
  public PaymentMethodType? PaymentMethodType { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("paymentToken")]
  public string? PaymentToken { get; set; }

  [Range(0, 2147483647)]
  [System.Text.Json.Serialization.JsonPropertyName("additionalSeats")]
  public int? AdditionalSeats { get; set; }

  [Range(0, 99)]
  [System.Text.Json.Serialization.JsonPropertyName("additionalStorageGb")]
  public int? AdditionalStorageGb { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("premiumAccessAddon")]
  public bool? PremiumAccessAddon { get; set; }

  [MinLength(0)]
  [MaxLength(1000)]
  [System.Text.Json.Serialization.JsonPropertyName("collectionName")]
  public string? CollectionName { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("taxIdNumber")]
  public string? TaxIdNumber { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("billingAddressLine1")]
  public string? BillingAddressLine1 { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("billingAddressLine2")]
  public string? BillingAddressLine2 { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("billingAddressCity")]
  public string? BillingAddressCity { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("billingAddressState")]
  public string? BillingAddressState { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("billingAddressPostalCode")]
  public string? BillingAddressPostalCode { get; set; }

  [MinLength(0)]
  [MaxLength(2)]
  [System.Text.Json.Serialization.JsonPropertyName("billingAddressCountry")]
  public string? BillingAddressCountry { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("maxAutoscaleSeats")]
  public int? MaxAutoscaleSeats { get; set; }

  [Range(0, 2147483647)]
  [System.Text.Json.Serialization.JsonPropertyName("additionalSmSeats")]
  public int? AdditionalSmSeats { get; set; }

  [Range(0, 2147483647)]
  [System.Text.Json.Serialization.JsonPropertyName("additionalServiceAccounts")]
  public int? AdditionalServiceAccounts { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("useSecretsManager")]
  public bool UseSecretsManager { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("isFromSecretsManagerTrial")]
  public bool? IsFromSecretsManagerTrial { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("initiationPath")]
  public string? InitiationPath { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("skipTrial")]
  public bool? SkipTrial { get; set; }
}
