//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// OtherDeviceKeysUpdateRequestModel from OpenAPI schema.
/// Schema path: #/components/schemas/OtherDeviceKeysUpdateRequestModel
/// </summary>
public class OtherDeviceKeysUpdateRequestModel
{
  [Required]
  [MinLength(1)]
  [System.Text.Json.Serialization.JsonPropertyName("encryptedPublicKey")]
  public string? EncryptedPublicKey { get; set; }

  [Required]
  [MinLength(1)]
  [System.Text.Json.Serialization.JsonPropertyName("encryptedUserKey")]
  public string? EncryptedUserKey { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("deviceId")]
  public Guid DeviceId { get; set; }
}
