//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// PasswordPreloginRequestModel from OpenAPI schema.
/// Schema path: #/components/schemas/PasswordPreloginRequestModel
/// </summary>
public class PasswordPreloginRequestModel
{
  [Required]
  [MinLength(0)]
  [MaxLength(256)]
  [EmailAddress]
  [System.Text.Json.Serialization.JsonPropertyName("email")]
  public string? Email { get; set; }
}
