//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// PasswordManagerPlanFeaturesResponseModel from OpenAPI schema.
/// Schema path: #/components/schemas/PasswordManagerPlanFeaturesResponseModel
/// </summary>
public class PasswordManagerPlanFeaturesResponseModel
{
  [System.Text.Json.Serialization.JsonPropertyName("stripePlanId")]
  public string? StripePlanId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("stripeSeatPlanId")]
  public string? StripeSeatPlanId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("stripeProviderPortalSeatPlanId")]
  public string? StripeProviderPortalSeatPlanId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("basePrice")]
  public double? BasePrice { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("seatPrice")]
  public double? SeatPrice { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("providerPortalSeatPrice")]
  public double? ProviderPortalSeatPrice { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("allowSeatAutoscale")]
  public bool? AllowSeatAutoscale { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("hasAdditionalSeatsOption")]
  public bool? HasAdditionalSeatsOption { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("maxAdditionalSeats")]
  public int? MaxAdditionalSeats { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("baseSeats")]
  public int? BaseSeats { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("hasPremiumAccessOption")]
  public bool? HasPremiumAccessOption { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("stripePremiumAccessPlanId")]
  public string? StripePremiumAccessPlanId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("premiumAccessOptionPrice")]
  public double? PremiumAccessOptionPrice { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("maxSeats")]
  public int? MaxSeats { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("baseStorageGb")]
  public int? BaseStorageGb { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("hasAdditionalStorageOption")]
  public bool? HasAdditionalStorageOption { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("additionalStoragePricePerGb")]
  public double? AdditionalStoragePricePerGb { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("stripeStoragePlanId")]
  public string? StripeStoragePlanId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("maxAdditionalStorage")]
  public int? MaxAdditionalStorage { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("maxCollections")]
  public int? MaxCollections { get; set; }
}
