//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// PendingAuthRequestResponseModel from OpenAPI schema.
/// Schema path: #/components/schemas/PendingAuthRequestResponseModel
/// </summary>
public class PendingAuthRequestResponseModel
{
  [System.Text.Json.Serialization.JsonPropertyName("object")]
  public string? Object { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public Guid? Id { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("publicKey")]
  public string? PublicKey { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("requestDeviceIdentifier")]
  public string? RequestDeviceIdentifier { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("requestDeviceTypeValue")]
  public DeviceType? RequestDeviceTypeValue { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("requestDeviceType")]
  public string? RequestDeviceType { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("requestIpAddress")]
  public string? RequestIpAddress { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("requestCountryName")]
  public string? RequestCountryName { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("key")]
  public string? Key { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("masterPasswordHash")]
  public string? MasterPasswordHash { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("creationDate")]
  public DateTime? CreationDate { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("responseDate")]
  public DateTime? ResponseDate { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("requestApproved")]
  public bool? RequestApproved { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("origin")]
  public string? Origin { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("requestDeviceId")]
  public Guid? RequestDeviceId { get; set; }
}
