//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// Permissions from OpenAPI schema.
/// Schema path: #/components/schemas/Permissions
/// </summary>
public class Permissions
{
  [System.Text.Json.Serialization.JsonPropertyName("accessEventLogs")]
  public bool? AccessEventLogs { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("accessImportExport")]
  public bool? AccessImportExport { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("accessReports")]
  public bool? AccessReports { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("createNewCollections")]
  public bool? CreateNewCollections { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("editAnyCollection")]
  public bool? EditAnyCollection { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("deleteAnyCollection")]
  public bool? DeleteAnyCollection { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("manageGroups")]
  public bool? ManageGroups { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("managePolicies")]
  public bool? ManagePolicies { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("manageSso")]
  public bool? ManageSso { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("manageUsers")]
  public bool? ManageUsers { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("manageResetPassword")]
  public bool? ManageResetPassword { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("manageScim")]
  public bool? ManageScim { get; set; }
}
