//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// PlanResponseModel from OpenAPI schema.
/// Schema path: #/components/schemas/PlanResponseModel
/// </summary>
public class PlanResponseModel
{
  [System.Text.Json.Serialization.JsonPropertyName("object")]
  public string? Object { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public PlanType? Type { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("productTier")]
  public ProductTierType? ProductTier { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("isAnnual")]
  public bool? IsAnnual { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("nameLocalizationKey")]
  public string? NameLocalizationKey { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("descriptionLocalizationKey")]
  public string? DescriptionLocalizationKey { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("canBeUsedByBusiness")]
  public bool? CanBeUsedByBusiness { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("trialPeriodDays")]
  public int? TrialPeriodDays { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("hasSelfHost")]
  public bool? HasSelfHost { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("hasPolicies")]
  public bool? HasPolicies { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("hasGroups")]
  public bool? HasGroups { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("hasDirectory")]
  public bool? HasDirectory { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("hasEvents")]
  public bool? HasEvents { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("hasTotp")]
  public bool? HasTotp { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("has2fa")]
  public bool? Has2Fa { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("hasApi")]
  public bool? HasApi { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("hasSso")]
  public bool? HasSso { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("hasOrganizationDomains")]
  public bool? HasOrganizationDomains { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("hasResetPassword")]
  public bool? HasResetPassword { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("usersGetPremium")]
  public bool? UsersGetPremium { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("upgradeSortOrder")]
  public int? UpgradeSortOrder { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("displaySortOrder")]
  public int? DisplaySortOrder { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("legacyYear")]
  public int? LegacyYear { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("disabled")]
  public bool? Disabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("secretsManager")]
  public SecretsManagerPlanFeaturesResponseModel? SecretsManager { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("passwordManager")]
  public PasswordManagerPlanFeaturesResponseModel? PasswordManager { get; set; }
}
