//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// Represents PlanType values
/// </summary>
public enum PlanType
{
    [EnumMember(Value = "0")]
    Free = 0,

    [EnumMember(Value = "1")]
    FamiliesAnnually2019 = 1,

    [EnumMember(Value = "2")]
    TeamsMonthly2019 = 2,

    [EnumMember(Value = "3")]
    TeamsAnnually2019 = 3,

    [EnumMember(Value = "4")]
    EnterpriseMonthly2019 = 4,

    [EnumMember(Value = "5")]
    EnterpriseAnnually2019 = 5,

    [EnumMember(Value = "6")]
    Custom = 6,

    [EnumMember(Value = "7")]
    FamiliesAnnually2025 = 7,

    [EnumMember(Value = "8")]
    TeamsMonthly2020 = 8,

    [EnumMember(Value = "9")]
    TeamsAnnually2020 = 9,

    [EnumMember(Value = "10")]
    EnterpriseMonthly2020 = 10,

    [EnumMember(Value = "11")]
    EnterpriseAnnually2020 = 11,

    [EnumMember(Value = "12")]
    TeamsMonthly2023 = 12,

    [EnumMember(Value = "13")]
    TeamsAnnually2023 = 13,

    [EnumMember(Value = "14")]
    EnterpriseMonthly2023 = 14,

    [EnumMember(Value = "15")]
    EnterpriseAnnually2023 = 15,

    [EnumMember(Value = "16")]
    TeamsStarter2023 = 16,

    [EnumMember(Value = "17")]
    TeamsMonthly = 17,

    [EnumMember(Value = "18")]
    TeamsAnnually = 18,

    [EnumMember(Value = "19")]
    EnterpriseMonthly = 19,

    [EnumMember(Value = "20")]
    EnterpriseAnnually = 20,

    [EnumMember(Value = "21")]
    TeamsStarter = 21,

    [EnumMember(Value = "22")]
    FamiliesAnnually = 22
}
