//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// Represents PolicyType values
/// </summary>
public enum PolicyType
{
    [EnumMember(Value = "0")]
    TwoFactorAuthentication = 0,

    [EnumMember(Value = "1")]
    MasterPassword = 1,

    [EnumMember(Value = "2")]
    PasswordGenerator = 2,

    [EnumMember(Value = "3")]
    SingleOrg = 3,

    [EnumMember(Value = "4")]
    RequireSso = 4,

    [EnumMember(Value = "5")]
    OrganizationDataOwnership = 5,

    [EnumMember(Value = "6")]
    DisableSend = 6,

    [EnumMember(Value = "7")]
    SendOptions = 7,

    [EnumMember(Value = "8")]
    ResetPassword = 8,

    [EnumMember(Value = "9")]
    MaximumVaultTimeout = 9,

    [EnumMember(Value = "10")]
    DisablePersonalVaultExport = 10,

    [EnumMember(Value = "11")]
    ActivateAutofill = 11,

    [EnumMember(Value = "12")]
    AutomaticAppLogIn = 12,

    [EnumMember(Value = "13")]
    FreeFamiliesSponsorshipPolicy = 13,

    [EnumMember(Value = "14")]
    RemoveUnlockWithPin = 14,

    [EnumMember(Value = "15")]
    RestrictedItemTypesPolicy = 15,

    [EnumMember(Value = "16")]
    UriMatchDefaults = 16,

    [EnumMember(Value = "17")]
    AutotypeDefaultSetting = 17,

    [EnumMember(Value = "18")]
    AutomaticUserConfirmation = 18,

    [EnumMember(Value = "19")]
    BlockClaimedDomainAccountCreation = 19
}
