//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// PrivateKeysResponseModel from OpenAPI schema.
/// Schema path: #/components/schemas/PrivateKeysResponseModel
/// 
/// This response model is used to return the asymmetric encryption keys,
/// and signature keys of an entity. This includes the private keys of the key pairs,
/// (private key, signing key), and the public keys of the key pairs (unsigned public key,
/// signed public key, verification key).
/// </summary>
public class PrivateKeysResponseModel
{
  [System.Text.Json.Serialization.JsonPropertyName("object")]
  public string? Object { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("signatureKeyPair")]
  public SignatureKeyPairResponseModel? SignatureKeyPair { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("publicKeyEncryptionKeyPair")]
  public PublicKeyEncryptionKeyPairResponseModel PublicKeyEncryptionKeyPair { get; set; } = null!;

  [System.Text.Json.Serialization.JsonPropertyName("securityState")]
  public SecurityStateModel? SecurityState { get; set; }
}
