//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// ProfileProviderResponseModel from OpenAPI schema.
/// Schema path: #/components/schemas/ProfileProviderResponseModel
/// </summary>
public class ProfileProviderResponseModel
{
  [System.Text.Json.Serialization.JsonPropertyName("object")]
  public string? Object { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public Guid? Id { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("key")]
  public string? Key { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("status")]
  public ProviderUserStatusType? Status { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public ProviderUserType? Type { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("enabled")]
  public bool? Enabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("permissions")]
  public Permissions? Permissions { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("userId")]
  public Guid? UserId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("useEvents")]
  public bool? UseEvents { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("providerStatus")]
  public ProviderStatusType? ProviderStatus { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("providerType")]
  public ProviderType? ProviderType { get; set; }
}
