//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// ProfileResponseModel from OpenAPI schema.
/// Schema path: #/components/schemas/ProfileResponseModel
/// </summary>
public class ProfileResponseModel
{
  [System.Text.Json.Serialization.JsonPropertyName("object")]
  public string? Object { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public Guid? Id { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("email")]
  public string? Email { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("emailVerified")]
  public bool? EmailVerified { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("premium")]
  public bool? Premium { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("premiumFromOrganization")]
  public bool? PremiumFromOrganization { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("culture")]
  public string? Culture { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("twoFactorEnabled")]
  public bool? TwoFactorEnabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("key")]
  public string? Key { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("privateKey")]
  public string? PrivateKey { get; set; }

  /// <summary>
  /// This response model is used to return the asymmetric encryption keys,
  /// and signature keys of an entity. This includes the private keys of the key pairs,
  /// (private key, signing key), and the public keys of the key pairs (unsigned public key,
  /// signed public key, verification key).
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("accountKeys")]
  public PrivateKeysResponseModel? AccountKeys { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("securityStamp")]
  public string? SecurityStamp { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("forcePasswordReset")]
  public bool? ForcePasswordReset { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("usesKeyConnector")]
  public bool? UsesKeyConnector { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("avatarColor")]
  public string? AvatarColor { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("creationDate")]
  public DateTime? CreationDate { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("verifyDevices")]
  public bool? VerifyDevices { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("organizations")]
  public List<ProfileOrganizationResponseModel>? Organizations { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("providers")]
  public List<ProfileProviderResponseModel>? Providers { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("providerOrganizations")]
  public List<ProfileProviderOrganizationResponseModel>? ProviderOrganizations { get; set; }
}
