//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// ProfileOrganizationResponseModel from OpenAPI schema.
/// Schema path: #/components/schemas/ProfileOrganizationResponseModel
/// 
/// Sync data for organization members and their organization.
/// Note: see Bit.Api.AdminConsole.Models.Response.ProfileProviderOrganizationResponseModel for organization sync data received by provider users.
/// </summary>
public class ProfileOrganizationResponseModel
{
  [System.Text.Json.Serialization.JsonPropertyName("object")]
  public string? Object { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public Guid? Id { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("enabled")]
  public bool? Enabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("identifier")]
  public string? Identifier { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("productTierType")]
  public ProductTierType? ProductTierType { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("usePolicies")]
  public bool? UsePolicies { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("useSso")]
  public bool? UseSso { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("useKeyConnector")]
  public bool? UseKeyConnector { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("useScim")]
  public bool? UseScim { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("useGroups")]
  public bool? UseGroups { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("useDirectory")]
  public bool? UseDirectory { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("useEvents")]
  public bool? UseEvents { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("useTotp")]
  public bool? UseTotp { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("use2fa")]
  public bool? Use2Fa { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("useApi")]
  public bool? UseApi { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("useResetPassword")]
  public bool? UseResetPassword { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("useSecretsManager")]
  public bool? UseSecretsManager { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("usePasswordManager")]
  public bool? UsePasswordManager { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("usersGetPremium")]
  public bool? UsersGetPremium { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("useCustomPermissions")]
  public bool? UseCustomPermissions { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("useActivateAutofillPolicy")]
  public bool? UseActivateAutofillPolicy { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("useRiskInsights")]
  public bool? UseRiskInsights { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("useOrganizationDomains")]
  public bool? UseOrganizationDomains { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("useAdminSponsoredFamilies")]
  public bool? UseAdminSponsoredFamilies { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("useAutomaticUserConfirmation")]
  public bool? UseAutomaticUserConfirmation { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("selfHost")]
  public bool? SelfHost { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("seats")]
  public int? Seats { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("maxCollections")]
  public int? MaxCollections { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("maxStorageGb")]
  public int? MaxStorageGb { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("key")]
  public string? Key { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("hasPublicAndPrivateKeys")]
  public bool? HasPublicAndPrivateKeys { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("ssoBound")]
  public bool? SsoBound { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("resetPasswordEnrolled")]
  public bool? ResetPasswordEnrolled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("limitCollectionCreation")]
  public bool? LimitCollectionCreation { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("limitCollectionDeletion")]
  public bool? LimitCollectionDeletion { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("limitItemDeletion")]
  public bool? LimitItemDeletion { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("allowAdminAccessToAllCollectionItems")]
  public bool? AllowAdminAccessToAllCollectionItems { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("providerId")]
  public Guid? ProviderId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("providerName")]
  public string? ProviderName { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("providerType")]
  public ProviderType? ProviderType { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("ssoEnabled")]
  public bool? SsoEnabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("keyConnectorEnabled")]
  public bool? KeyConnectorEnabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("keyConnectorUrl")]
  public string? KeyConnectorUrl { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("ssoMemberDecryptionType")]
  public MemberDecryptionType? SsoMemberDecryptionType { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("accessSecretsManager")]
  public bool? AccessSecretsManager { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("userId")]
  public Guid? UserId { get; set; }

  /// <summary>
  /// Represents the different stages of a member&apos;s lifecycle in an organization.
  /// The Bit.Core.Entities.OrganizationUser object is populated differently depending on their Status.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("status")]
  public OrganizationUserStatusType? Status { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public OrganizationUserType? Type { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("permissions")]
  public Permissions? Permissions { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("organizationUserId")]
  public Guid? OrganizationUserId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("userIsClaimedByOrganization")]
  public bool? UserIsClaimedByOrganization { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("familySponsorshipFriendlyName")]
  public string? FamilySponsorshipFriendlyName { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("familySponsorshipAvailable")]
  public bool? FamilySponsorshipAvailable { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("familySponsorshipLastSyncDate")]
  public DateTime? FamilySponsorshipLastSyncDate { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("familySponsorshipValidUntil")]
  public DateTime? FamilySponsorshipValidUntil { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("familySponsorshipToDelete")]
  public bool? FamilySponsorshipToDelete { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("isAdminInitiated")]
  public bool? IsAdminInitiated { get; set; }

  /// <summary>
  /// Obsolete property for backward compatibility
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("userIsManagedByOrganization")]
  public bool? UserIsManagedByOrganization { get; set; }
}
