//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// Represents PushTechnologyType values
/// </summary>
public enum PushTechnologyType
{
    [EnumMember(Value = "0")]
    SignalR = 0,

    [EnumMember(Value = "1")]
    WebPush = 1
}
