//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// SecretsManagerPlanFeaturesResponseModel from OpenAPI schema.
/// Schema path: #/components/schemas/SecretsManagerPlanFeaturesResponseModel
/// </summary>
public class SecretsManagerPlanFeaturesResponseModel
{
  [System.Text.Json.Serialization.JsonPropertyName("maxServiceAccounts")]
  public int? MaxServiceAccounts { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("allowServiceAccountsAutoscale")]
  public bool? AllowServiceAccountsAutoscale { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("stripeServiceAccountPlanId")]
  public string? StripeServiceAccountPlanId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("additionalPricePerServiceAccount")]
  public double? AdditionalPricePerServiceAccount { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("baseServiceAccount")]
  public int? BaseServiceAccount { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("maxAdditionalServiceAccount")]
  public int? MaxAdditionalServiceAccount { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("hasAdditionalServiceAccountOption")]
  public bool? HasAdditionalServiceAccountOption { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("stripeSeatPlanId")]
  public string? StripeSeatPlanId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("hasAdditionalSeatsOption")]
  public bool? HasAdditionalSeatsOption { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("basePrice")]
  public double? BasePrice { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("seatPrice")]
  public double? SeatPrice { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("baseSeats")]
  public int? BaseSeats { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("maxSeats")]
  public int? MaxSeats { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("maxAdditionalSeats")]
  public int? MaxAdditionalSeats { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("allowSeatAutoscale")]
  public bool? AllowSeatAutoscale { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("maxProjects")]
  public int? MaxProjects { get; set; }
}
