//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// SecurityTasksResponseModel from OpenAPI schema.
/// Schema path: #/components/schemas/SecurityTasksResponseModel
/// </summary>
public class SecurityTasksResponseModel
{
  [System.Text.Json.Serialization.JsonPropertyName("object")]
  public string? Object { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public Guid? Id { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("organizationId")]
  public Guid? OrganizationId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("cipherId")]
  public Guid? CipherId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public SecurityTaskType? Type { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("status")]
  public SecurityTaskStatus? Status { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("creationDate")]
  public DateTime? CreationDate { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("revisionDate")]
  public DateTime? RevisionDate { get; set; }
}
