//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// SendRequestModel from OpenAPI schema.
/// Schema path: #/components/schemas/SendRequestModel
/// </summary>
public class SendRequestModel
{
  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public SendType? Type { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("fileLength")]
  public long? FileLength { get; set; }

  [MinLength(0)]
  [MaxLength(1000)]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  [MinLength(0)]
  [MaxLength(1000)]
  [System.Text.Json.Serialization.JsonPropertyName("notes")]
  public string? Notes { get; set; }

  [Required]
  [MinLength(0)]
  [MaxLength(1000)]
  [System.Text.Json.Serialization.JsonPropertyName("key")]
  public string? Key { get; set; }

  [Range(1, 2147483647)]
  [System.Text.Json.Serialization.JsonPropertyName("maxAccessCount")]
  public int? MaxAccessCount { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("expirationDate")]
  public DateTime? ExpirationDate { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("deletionDate")]
  public DateTime DeletionDate { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("file")]
  public SendFileModel? File { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("text")]
  public SendTextModel? Text { get; set; }

  [MinLength(0)]
  [MaxLength(1000)]
  [System.Text.Json.Serialization.JsonPropertyName("password")]
  public string? Password { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("disabled")]
  public bool Disabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("hideEmail")]
  public bool? HideEmail { get; set; }
}
