//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// SendResponseModel from OpenAPI schema.
/// Schema path: #/components/schemas/SendResponseModel
/// </summary>
public class SendResponseModel
{
  [System.Text.Json.Serialization.JsonPropertyName("object")]
  public string? Object { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public Guid? Id { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("accessId")]
  public string? AccessId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public SendType? Type { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("notes")]
  public string? Notes { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("file")]
  public SendFileModel? File { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("text")]
  public SendTextModel? Text { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("key")]
  public string? Key { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("maxAccessCount")]
  public int? MaxAccessCount { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("accessCount")]
  public int? AccessCount { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("password")]
  public string? Password { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("disabled")]
  public bool? Disabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("revisionDate")]
  public DateTime? RevisionDate { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("expirationDate")]
  public DateTime? ExpirationDate { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("deletionDate")]
  public DateTime? DeletionDate { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("hideEmail")]
  public bool? HideEmail { get; set; }
}
