//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// SignatureKeyPairRequestModel from OpenAPI schema.
/// Schema path: #/components/schemas/SignatureKeyPairRequestModel
/// </summary>
public class SignatureKeyPairRequestModel
{
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("signatureAlgorithm")]
  public string? SignatureAlgorithm { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("wrappedSigningKey")]
  public string? WrappedSigningKey { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("verifyingKey")]
  public string? VerifyingKey { get; set; }
}
