//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// SyncResponseModel from OpenAPI schema.
/// Schema path: #/components/schemas/SyncResponseModel
/// </summary>
public class SyncResponseModel
{
  [System.Text.Json.Serialization.JsonPropertyName("object")]
  public string? Object { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("profile")]
  public ProfileResponseModel? Profile { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("folders")]
  public List<FolderResponseModel>? Folders { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("collections")]
  public List<CollectionDetailsResponseModel>? Collections { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("ciphers")]
  public List<CipherDetailsResponseModel>? Ciphers { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("domains")]
  public DomainsResponseModel? Domains { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("policies")]
  public List<PolicyResponseModel>? Policies { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("sends")]
  public List<SendResponseModel>? Sends { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("userDecryption")]
  public UserDecryptionResponseModel? UserDecryption { get; set; }
}
