//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// TokenErrorResponse from OpenAPI schema.
/// Schema path: #/components/schemas/TokenErrorResponse
/// </summary>
public class TokenErrorResponse
{
  [System.Text.Json.Serialization.JsonPropertyName("error")]
  public string? Error { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("error_description")]
  public string? ErrorDescription { get; set; }

  /// <summary>
  /// Available 2FA provider types when 2FA is required
  /// </summary>
  public List<int>? TwoFactorProviders { get; set; }

  /// <summary>
  /// Detailed 2FA provider info keyed by provider type
  /// </summary>
  public object? TwoFactorProviders2 { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("SsoEmail2faSessionToken")]
  public string? SsoEmail2FaSessionToken { get; set; }

  public object? MasterPasswordPolicy { get; set; }
}
