//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// TokenResponse from OpenAPI schema.
/// Schema path: #/components/schemas/TokenResponse
/// </summary>
public class TokenResponse
{
  [System.Text.Json.Serialization.JsonPropertyName("access_token")]
  public string? AccessToken { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("expires_in")]
  public int? ExpiresIn { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("token_type")]
  public string? TokenType { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("refresh_token")]
  public string? RefreshToken { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("scope")]
  public string? Scope { get; set; }

  /// <summary>
  /// RSA private key encrypted with the user symmetric key
  /// </summary>
  public string? PrivateKey { get; set; }

  /// <summary>
  /// Protected symmetric key encrypted with the stretched master key
  /// </summary>
  public string? Key { get; set; }

  /// <summary>
  /// KDF type: 0=PBKDF2_SHA256, 1=Argon2id
  /// </summary>
  public int? Kdf { get; set; }

  public int? KdfIterations { get; set; }

  public int? KdfMemory { get; set; }

  public int? KdfParallelism { get; set; }

  public bool? ForcePasswordReset { get; set; }

  public bool? ResetMasterPassword { get; set; }

  public object? MasterPasswordPolicy { get; set; }

  public object? UserDecryptionOptions { get; set; }
}
