//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// UpdateTwoFactorAuthenticatorRequestModel from OpenAPI schema.
/// Schema path: #/components/schemas/UpdateTwoFactorAuthenticatorRequestModel
/// </summary>
public class UpdateTwoFactorAuthenticatorRequestModel
{
  [MinLength(0)]
  [MaxLength(300)]
  [System.Text.Json.Serialization.JsonPropertyName("masterPasswordHash")]
  public string? MasterPasswordHash { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("otp")]
  public string? Otp { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("authRequestAccessCode")]
  public string? AuthRequestAccessCode { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("secret")]
  public string? Secret { get; set; }

  [Required]
  [MinLength(0)]
  [MaxLength(50)]
  [System.Text.Json.Serialization.JsonPropertyName("token")]
  public string? Token { get; set; }

  [Required]
  [MinLength(0)]
  [MaxLength(50)]
  [System.Text.Json.Serialization.JsonPropertyName("key")]
  public string? Key { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("userVerificationToken")]
  public string? UserVerificationToken { get; set; }
}
