//
// <auto-generated>
// Generated by: ApiGenerator
// Source: specs/vaultwarden-identity.json
// API: Vaultwarden Identity 1.35.4 (API 2025.12.0) + Vaultwarden Vault 1.35.4 (API 2025.12.0) + Vaultwarden Public 1.35.4 (API 2025.12.0)
// Version: 1.35.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable

namespace Apigen.Vaultwarden.Models;

/// <summary>
/// UpdateTwoFactorYubicoOtpRequestModel from OpenAPI schema.
/// Schema path: #/components/schemas/UpdateTwoFactorYubicoOtpRequestModel
/// </summary>
public class UpdateTwoFactorYubicoOtpRequestModel
{
  [MinLength(0)]
  [MaxLength(300)]
  [System.Text.Json.Serialization.JsonPropertyName("masterPasswordHash")]
  public string? MasterPasswordHash { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("otp")]
  public string? Otp { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("authRequestAccessCode")]
  public string? AuthRequestAccessCode { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("secret")]
  public string? Secret { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("key1")]
  public string? Key1 { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("key2")]
  public string? Key2 { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("key3")]
  public string? Key3 { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("key4")]
  public string? Key4 { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("key5")]
  public string? Key5 { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("nfc")]
  public bool Nfc { get; set; }
}
